### PR TITLE
bumped version to 2020.8.0

### PR DESCRIPTION
**Pull request by sjvrijn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)

* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
Hi, 

the package failed to upload because of an outage of anaconda.org. If oyu push an empty commit to master, the CI will be triggered and the updated package should be uploaded.

**Comment by sjvrijn** [comment]
Thanks for the notification, will do 👍

**Comment by sjvrijn** [comment]
Hi @wolfv, I've tried rebuilding twice, but it still fails to upload, see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=200877&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=673

Any idea what's happening and what I can do to fix it?

**Comment by sjvrijn** [comment]
@wolfv Nevermind, a rerender has solved the issue.

**Pull request merged**
